### ISSUE TITLE
Publish shutter-encoder builds to winget-pkgs + auto winget-releaser GA

### ISSUE THREAD

**Issue by jo-chemla** [paulpacifico/shutter-encoder#244]
To streamline installation of shutter-encoder, it could be useful to have: 
 - the shutter-encoder builds pushed as github-releases for anyone to access them
 - and in parallel, a winget package so that windosw people can install shutter-encoder via a simple `winget install shutter-encoder`

## Winget package name

Initial publishing on [winget-pkgs](https://github.com/microsoft/winget-pkgs) can be done via a utility like [Komac](https://github.com/russellbanks/Komac). You would need to determine:
 - a package identifier, probably along the lines of `paulpacifico.shutter-encoder`
 - the installer url, eg [installer](https://www.shutterencoder.com/sdc_download/468/?key=5aghbpajxm25ylrly4xtk3oo1d8nkg) and [portable](https://www.shutterencoder.com/sdc_download/493/?key=sy795vosksen2xx1vlfboq2ebknb9w). Note that this package url need to be valid any time, since this is where the install command will fetch the package. There seem to be a key url-param, if that url breaks after a few hours/days, then the package validation will fail.
 - and a few other metadata that mostly anyone can populate. Initial release would allow anyone to install the software with the above `winget install` command. 

That initial publishing can be done by either you or any community member. 

## Automated Github action workflow to push new package on github release

In order to simplify the process of pushing new releases automatically to winget-pkgs, adding a github action on this repo could be useful so that the winget `shutter-encoder` package gets updated on every github release.

Here is a reference article based on [Winget-Releaser@v2 Github Action](https://github.com/russellbanks/Komac?tab=readme-ov-file#usage-with-github-actions-winget-releaser-) 

There is no need for code signing mentioned in this issue; https://github.com/paulpacifico/shutter-encoder/issues/101

Below is an action yml files made to keep the winget package up-to-date on every github release, via Github Actions. 

```yaml
name: Publish to WinGet
on:
  release:
    types: [ released ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: paulpacifico.shutter-encoder
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: '\-windows\-\w*\.zip$' 
```

Requires:
 - You will need to create a classic Personal Access Token (PAT) with public_repo scope.
 - This token should be added as a repository secret by creating a [new repo secret](https://github.com/Jacalz/rymdport/settings/secrets/actions/new) with name WINGET_ACC_TOKEN and value the token
 - Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under the same account/organization as the project's repository. If you are forking winget-pkgs on a different account (e.g. bot/personal account), you can use the fork-user input to specify the username of the account where the fork is present.
